name: Auto Deploy ke HomeServer

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: autoDeploy
        run: |
          curl -X POST https://mogamogapecahtelor.faaruq.com/api/update \
            -H "Authorization: Bearer ${{ secrets.API_PASSWORD }}" \
            -H "Content-Type: application/json" \
            --fail --show-error
